version: 2.1
orbs:
  service-orb: g66/service@dev:DO-77

commands:
  install_aws_cli:
    description: "Install AWS CLI"
    steps:
      - run:
          name: install aws cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
jobs:
  release:

    docker:
      - image: circleci/python:3.10

    steps:
      - checkout
      - install_aws_cli
      - service-orb/codeartifact_login:
          tool: twine

      - run:
          name: upload nameko tracer package
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install twine build
            python -m build
            twine upload dist/* --repository codeartifact

workflows:
  version: 2
  do-it-all:
    jobs:
      - approval:
          # filters:
          #   branches:
          #     only: master
          context: org-global
          type: approval
          # requires:
          #   - test
      - release:
          context: org-global
          requires:
            - approval
